import mysql.connector
import tkinter as tk
import tkinter.messagebox as tm
def insert():
    def put():
        roll=RollNo.get()
        name=Name.get()
        admno=Admno.get()
        Clss=Clas.get()
        Dob=dob.get()
        gender=Gender.get()
        mydb = mysql.connector.connect(host="localhost",  user="root", passwd="1234",  database="school")
        mycursor = mydb.cursor()
        mycursor.execute("INSERT INTO details VALUES('"+admno+"','"+roll+"','"+str(name)+"','"+str(Clss)+"','"+str(gender)+"','"+Dob+"')")
        mydb.commit()
        mydb.close()
        print(mycursor.rowcount,"RECORDS INSERTED")
        tm.showinfo("Alert Message", "Record has been inserted successfully")
    Admno = tk.Entry(window,width="20")
    Admnolabel = tk.Label(window,text="Enter the Admission number")
    Admnolabel.place(x = 80, y = 30)
    Admno.place(x =250, y = 30)
    RollNo = tk.Entry(window,width="20")
    RollNolabel = tk.Label(window,text="Enter Roll number")
    RollNolabel.place(x = 80, y = 50)
    RollNo.place(x = 250, y = 50)
    Name = tk.Entry(window,width="20")
    Namelabel = tk.Label(window,text="Enter the name")
    Namelabel.place(x = 80, y = 70)
    Name.place(x = 250, y = 70)
    Clas = tk.Entry(window,width="20")
    Claslabel = tk.Label(window,text="Enter Class")
    Claslabel.place(x = 80, y = 90)
    Clas.place(x = 250, y = 90)
    Gender = tk.Entry(window,width="20")
    Genderlabel = tk.Label(window,text="Enter Gender(M/F)")
    Genderlabel.place(x = 80, y = 110)
    Gender.place(x = 250, y = 110)
    dob = tk.Entry(window,width="20")
    doblabel = tk.Label(window,text="Enter D.O.B.(YYY-MM-DD)")
    doblabel.place(x = 80, y = 130)
    dob.place(x = 250, y = 130)
    enter = tk.Button(window,text="Enter The Record", command=put)
    enter.place(x = 150, y = 160)
    window.mainloop()
def delete():
    def clear():
        admno=Admno.get()
        mydb = mysql.connector.connect(  host="localhost",  user="root",passwd="1234",  database="school")
        mycursor = mydb.cursor()
        mycursor.execute("delete from details where admno='"+admno+"'")
        mydb.commit()
        mydb.close()
        print(mycursor.rowcount,"RECORDS Deleted")
        tm.showinfo("Alert Message", "Record has been deleted successfully")
    Admno = tk.Entry(window,width="20")
    Admnolabel = tk.Label(window,text="Enter the Admission number")
    Admnolabel.place(x = 450, y = 30)
    Admno.place(x = 620, y = 30)
    enter = tk.Button(window,text="Delete The Record", command=clear,fg="blue")
    enter.place(x = 500, y = 70)
    window.mainloop()
def update():
    def name():
        def nm():
            admno=Admno.get()
            name=Name.get()
            mydb = mysql.connector.connect(  host="localhost",  user="root",passwd="1234",  database="school")
            mycursor = mydb.cursor()
            mycursor.execute("update details set name='"+name+"' where ADMNO='"+admno+"'")
            mydb.commit()
            mydb.close()
            print(mycursor.rowcount,"Name updated")
            tm.showinfo("Alert Message", "Record has been updated successfully")
        Name = tk.Entry(window,width="20")
        Namelabel = tk.Label(window,text="Enter the name")
        Namelabel.place(x =10, y =300)
        Name.place(x = 100, y = 300)
        enter = tk.Button(window,text="Update The Name", command=nm)
        enter.place(x = 50, y = 340)
        window.mainloop()
    def roll():
        def rl():
            admno=Admno.get()
            roll=Roll.get()
            mydb = mysql.connector.connect(  host="localhost",  user="root",passwd="1234",  database="school")
            mycursor = mydb.cursor()
            mycursor.execute("update std set roll='"+roll+"' where ADMNO='"+admno+"'")
            mydb.commit()
            mydb.close()
            print(mycursor.rowcount,"Name updated")
            tm.showinfo("Alert Message", "Record has been updated successfully")
        RollNo = tk.Entry(window,width="20")
        RollNolabel = tk.Label(window,text="Enter Roll number")
        RollNolabel.place(x = 270, y = 300)
        RollNo.place(x = 380, y = 300)
        enter = tk.Button(window,text="Update Roll", command=rl)
        enter.place(x = 360, y = 340)
        window.mainloop()
    def dob():
        def db():
            dob=Dob.get()
            admno=Admno.get()
            mydb = mysql.connector.connect(  host="localhost",  user="root",passwd="1234",  database="school")
            mycursor = mydb.cursor()
            mycursor.execute("update details set DOB='"+dob+"' where ADMNO='"+admno+"'")
            mydb.commit()
            mydb.close()
            print(mycursor.rowcount,"Name updated")
            tm.showinfo("Alert Message", "Record has been updated successfully") 
        Dob = tk.Entry(window,width="20")
        Doblabel = tk.Label(window,text="Enter New D.O.B(YYY-MM-DD) ")
        Doblabel.place(x = 550, y = 300)
        Dob.place(x = 730, y = 300)
        ent = tk.Button(window,text="Update DOB", command=db)
        ent.place(x = 650, y = 340)
        window.mainloop()
    Admno = tk.Entry(window,width="20")
    Admnolabel = tk.Label(window,text="Enter the Admission number")
    Admnolabel.place(x = 250, y = 230)
    Admno.place(x = 410, y = 230)
    enter = tk.Button(window,text="Update Name", command=name)
    enter.place(x = 50, y = 270)
    enter = tk.Button(window,text="Update Roll No", command=roll)
    enter.place(x = 350, y = 270)
    enter = tk.Button(window,text="Update D.O.B", command=dob)
    enter.place(x = 650, y = 270)
    window.mainloop()
def show():
    mydb = mysql.connector.connect(  host="localhost",  user="root",passwd="1234",  database="school")
    cursor = mydb.cursor()        
    data= cursor.fetchall()
    count=cursor.rowcount
    print("total no. of rows retrieved in resultset",count)
    for row in data:
        print(row)
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="1234",
  database="school"
)
window = tk.Tk()
window.geometry("880x700")
window.title("Simple Example to Insert")
enter = tk.Button(window,text="Enter The Record", command=insert,fg="green")
enter.place(x = 150, y =0)
Clear = tk.Button(window,text="Clear The Record", command=delete,fg="red")
Clear.place(x = 500, y =0)
update= tk.Button(window,text="Update The Record", command=update,fg="purple")
update.place(x = 340, y =200)
enter = tk.Button(window,text="Enter The Record", command=show,fg="green")
enter.place(x = 350, y =500)

window.mainloop()

